### ISSUE TITLE
Addding limited Ability descriptors

### ISSUE THREAD

**Issue by wishinghand** [kbedell/quest-vtt#18]
It seems that the Quest Creators Resource allows for limited descriptions of roles and abilities. Page 8 mentions that the creators provide simple reference information for this sort of thing. Page 27 then has the stock roles and abilities listed, albeit in a much less verbose form. I'd be willing to figure out how the module system works and make a pull request.

**Comment by kbedell** [comment]
Hi! Thanks so much for your interest, and your offer! I am in the middle of, what I am calling, a 2.0 release. This release has lots of surprises such as the ability to "enable" the loading of the Creator's Content material. The data entry is all done, its just a matter of setting up the back end. This release will be coming out probably in the next week or two depending on... well me. :)

**Comment by wishinghand** [comment]
Ok cool, good to know!
