### ISSUE TITLE
"update failed" attempting to update from 1.10.3 to 1.10.4

### ISSUE THREAD

**Issue by RangerRick** [kbedell/quest-vtt#22]
**Describe the bug**
When I go into my Foundry UI and attempt to update `quest-vtt` it throws an error saying "Not Found".

**To Reproduce**
1. Go to "Game Systems"
2. Click on "Update All"
3. See error

**Screenshots**
<img width="977" alt="Screen Shot 2020-10-20 at 5 29 43 PM" src="https://user-images.githubusercontent.com/89252/96646300-f0bce500-12f9-11eb-992b-3c2b0e6962c4.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.7
 - Browser Firefox
 - Version 81.0.2

**Additional context**
Server version 0.6.6 using docker image `felddy/foundryvtt`

**Comment by kbedell** [comment]
Hi,

Thanks for bringing this issue to my attention. There was a typo in the release name, which prevented the download of the zip file. You should be able to update to 1.10.4.

**Comment by RangerRick** [comment]
Yup! Thanks.
