### ISSUE TITLE
Cannot Add Effects and Ranges

### ISSUE THREAD

**Issue by crlong02** [kbedell/quest-vtt#24]
**Describe the bug**
Foundry 0.7.9

After creating compendiums as instructed in the instructions, when it comes time to create Abilities, it is not possible to save the effects or ranges.

**To Reproduce**
1. Go to Items
2. Click on Create Item
3. Create a new ability
4. Click Add Effect
5. Click Add Range
6. Attempt to save

**Expected behavior**
The Range saves and brings you back to the Effect window, whereupon you can click Save there and be returned to the Ability.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows on an AWS hosted Ubuntu server
 - Browser Edge
 - Version 87.0.664.75

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kbedell** [comment]
My apologies for the delay on this. You should now be able to add effects, and ranges. I've also added compatibility with So Nice Dice for visual dice rolling. Please let me know if you experience any other issues.

**Comment by crlong02** [comment]
This seems to be working fine now.  Have added numerous effects, ranges, etc.
